### ISSUE TITLE
"Actual" activation

### ISSUE THREAD

**Issue by cameronb23** [keygen-sh/example-electron-app#2]
This isn't so much a Keygen question, but is it possible to fetch the webpack bundle/app bundle only _after_ the user is authenticated?

**Comment by ezekg** [comment]
Sure, you could do something like:

```html
<script>
  const login = document.getElementById("login")

  login.addEventListener("submit", async event => {
    event.preventDefault()

    const email = document.getElementById("email")
    const password = document.getElementById("password")

    const { token, errors } = await authenticateUser(email.value, password.value)
    if (errors) {
      const [{ title, detail }] = errors
      alert(`${title}: ${detail}`)
      return false
    }

    // … load the bundle/app by inserting a script tag or using Node's require()
  })
</script>
```

And just FYI, that's taken directly from this example app, as it already does this—it loads `login.html`, and then after the user has authenticated it loads `index.html` via an IPC message sent to the main process from the renderer process, which then boots up the actual app.

Does that help? Or am I not understanding? 🙂

**Comment by cameronb23** [comment]
@ezekg I mean, I am using webpack JS bundles for my code, would there be any way to dynamically fetch the webpack sourcemapping only AFTER the user has authenticated successfully, and then run the bundle?

**Comment by ezekg** [comment]
Couldn’t you dynamically inject a script tag into the DOM which loads your bundle from e.g. `./dist/bundle.js` only after authenticating? Is there something that isn’t working for you that you’ve already tried? How would you normally load a webpack bundle for a web app?

**Comment by cameronb23** [comment]
Sorry, it is an Electron app that I am distributing. That is why I am concerned, and why I would like to fetch the sourcemapping from a remote server with authentication.

**Comment by ezekg** [comment]
Oh Okay, I think I understand now. So you could definitely load the webpack bundle from your server the same way you would from a web app. Better yet, you could even use [Keygen Dist](https://keygen.sh/distribution) to serve that bundle to make sure only licensed users can download it. 🙂

For example, you could use a URL like this to serve your bundle using Keygen Dist:

```
https://dist.keygen.sh/v1/{ACCOUNT}/{PRODUCT}/latest/bundle/js?key=bbec-988f-b52f-5188
```

Files will automatically require a valid license key in order to be downloaded.

**Comment by cameronb23** [comment]
But how would I load my webpack bundle from the server if all the code is generated into a webpack bundle? Maybe I am confused. Do you have any idea how I would implement this?

**Comment by ezekg** [comment]
A webpack bundle is simply an optimized, compiled, minified JavaScript file, right? You wouldn't necessarily be using Webpack with Electron, unless you absolutely wanted to, seeing as you can use most ES6 features and along with all of Node. But I'm assuming you don't want to include it in your app directly for some reason, probably because the source code would be exposed?

(That's a valid concern, but an Electron app can easily be modified to work around anything you do outside of compiling your code using something like [EncloseJS](http://enclosejs.com/) or another heavy form obfuscation. It's relatively simple to modify an Electron app's source code for an experienced developer.)

So you could just include something like below inside of your Electron app's code to dynamically load your bundle from a URL (something that e.g. Slack does),

```html
<script>
  const key = // … authenticate the user and get their valid license key

  // Inject the bundle into the Electron app at run-time
  const bundle = document.createElement('script')
  bundle.src = `https://dist.keygen.sh/v1/{ACCOUNT}/{PRODUCT}/latest/bundle/js?key=${key}`
  document.body.appendChild(bundle)
</script>
```

Does that make sense? Am I understanding correctly?

**Comment by cameronb23** [comment]
I understand what you are saying, but if the whole bundle is made into one file (including the startup electron bits), how would I separate them?

**Comment by cameronb23** [comment]
for reference, this is my current `main.dev.js` code:

```javascript
/* eslint global-require: 1, flowtype-errors/show-errors: 0 */

/**
 * This module executes inside of electron's main process. You can start
 * electron renderer process from here and communicate with the other processes
 * through IPC.
 *
 * When running `npm run build` or `npm run build-main`, this file is compiled to
 * `./app/main.prod.js` using webpack. This gives us some performance wins.
 *
 * @flow
 */
import { app, BrowserWindow, protocol, ipcMain } from 'electron';

import moment from 'moment';
import path from 'path';
import express from 'express';
import http from 'http';
import socket from 'socket.io';
import bodyParser from 'body-parser';

import { resetValidatedLicenses } from './keygen';

import MenuBuilder from './menu';

// Start the HTTP server to load Socket.io on
const server = http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/html' });
  res.end('<h1>Lightspeed Update Socket</h1>');
});

server.listen(8890);


const io = socket.listen(server);

const expressApp = express();
let expressServer;

let mainWindow = null;

if (process.env.NODE_ENV === 'production') {
  const sourceMapSupport = require('source-map-support');
  sourceMapSupport.install();
}

if (process.env.NODE_ENV === 'development' || process.env.DEBUG_PROD === 'true') {
  require('electron-debug')();
  const p = path.join(__dirname, '..', 'app', 'node_modules');
  require('module').globalPaths.push(p);
}

const installExtensions = async () => {
  const installer = require('electron-devtools-installer');
  const forceDownload = !!process.env.UPGRADE_EXTENSIONS;
  const extensions = [
    'REACT_DEVELOPER_TOOLS',
    'REDUX_DEVTOOLS'
  ];

  return Promise
    .all(extensions.map(name => installer.default(installer[name], forceDownload)))
    .catch(console.log);
};


/**
 * Add event listeners...
 */

app.on('window-all-closed', () => {
  expressServer.close();

  // Respect the OSX convention of having the application in memory even
  // after all windows have been closed

  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('ready', async () => {
  if (process.env.NODE_ENV === 'development' || process.env.DEBUG_PROD === 'true') {
    await installExtensions();
  }

  mainWindow = new BrowserWindow({
    show: false,
    width: 1024,
    height: 728,
    frame: false
  });

  // mainWindow.loadURL(`file://${__dirname}/app.html`);

  mainWindow.loadURL(`file://${__dirname}/activate.html`);

  ipcMain.on('unauthenticated', () => {
    resetValidatedLicenses();

    mainWindow.loadURL(`file://${__dirname}/activate.html`);
  });

  ipcMain.on('authenticated', () => {
    mainWindow.loadURL(`file://${__dirname}/app.html`);
  });

  // @TODO: Use 'ready-to-show' event
  //        https://github.com/electron/electron/blob/master/docs/api/browser-window.md#using-ready-to-show-event
  mainWindow.webContents.on('did-finish-load', () => {
    if (!mainWindow) {
      throw new Error('"mainWindow" is not defined');
    }
    mainWindow.show();
    mainWindow.focus();
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });

  const menuBuilder = new MenuBuilder(mainWindow);
  menuBuilder.buildMenu();
});

export default io;

```

**Comment by ezekg** [comment]
In that case, I don't think you're going to be able to accomplish that. The best you're likely going to get is injecting the client-side code into the renderer process i.e. the HTML pages. Injecting code into the main Electron process is likely not going to be possible and could pose a security concern i.e. you _could_ `eval` the code downloaded from a URL, but that's sketchy. You're better off packaging your main process code directly with the Electron app.

**Comment by cameronb23** [comment]
Do you have any suggestions then on how I could compile/obfuscate some integral files or the whole app codebase while at the same time using Keygen?

**Comment by ezekg** [comment]
You can use Keygen's APIs client-side without a problem as long as you authenticate as one of your users i.e. don't embed an admin auth token within the app. For obfuscation, Uglify will likely do the job (it can obfuscate pretty heavily, including strings), and then there's also the EncloseJS lib I linked to above, but I think you'd need to purchase it. I haven't used EncloseJS myself, but I've heard of Electron apps using it. In the end, it's all JS, so there's only so much you can do.

**Comment by cameronb23** [comment]
That's what I was thinking myself honestly. It's unfortunate but I have fallen in love with React+Electron so I guess it will have to do.

**Comment by ezekg** [comment]
Agreed, Electron is a great platform! I honestly wouldn’t worry too much about it. Getting traction is going to be the main goal, not deterring crackers. The crackers are gonna crack your software regardless of how hard you make it (eg I can crack Adobe’s software in about 5 mins), so the best you can do is obfuscate, and implement licensing + require a license for updates, initial download and support. Your time is better spent developing the app, especially since you’re building on JS. The majority of your users will play by the rules. 🙂
